name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  
  cloud_firestore: ^6.0.0
  firebase_core: ^4.0.0
  firebase_storage: ^13.0.0
  fl_chart: ^1.0.0
  flutter:
    sdk: flutter
  flutter_slidable: ^4.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  path: ^1.9.1
  path_provider: ^2.1.5
  provider: ^6.1.5

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app icon.jpeg"
  adaptive_icon_background: "#FFFFFF"  # Optional, Android only
  adaptive_icon_foreground: "assets/images/app icon.jpeg"
