// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJ_OqlwnchfUFVyfNzg2-ebQUsUP9YVXw',
    appId: '1:227719515296:web:ad0b50eebe0ae4fa2d0dc5',
    messagingSenderId: '227719515296',
    projectId: 'chatgpt-try-6dc6d',
    authDomain: 'chatgpt-try-6dc6d.firebaseapp.com',
    storageBucket: 'chatgpt-try-6dc6d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0wbHLU3V4ddhne7FjQ3BFrcRPlFlKerc',
    appId: '1:227719515296:android:0aa9773f1331bbf52d0dc5',
    messagingSenderId: '227719515296',
    projectId: 'chatgpt-try-6dc6d',
    storageBucket: 'chatgpt-try-6dc6d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwUJonuZ6KXM7AngZbh7etI-Yb_lOb9zE',
    appId: '1:227719515296:ios:3c18d62ceacd3cf42d0dc5',
    messagingSenderId: '227719515296',
    projectId: 'chatgpt-try-6dc6d',
    storageBucket: 'chatgpt-try-6dc6d.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwUJonuZ6KXM7AngZbh7etI-Yb_lOb9zE',
    appId: '1:227719515296:ios:3c18d62ceacd3cf42d0dc5',
    messagingSenderId: '227719515296',
    projectId: 'chatgpt-try-6dc6d',
    storageBucket: 'chatgpt-try-6dc6d.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJ_OqlwnchfUFVyfNzg2-ebQUsUP9YVXw',
    appId: '1:227719515296:web:f2454afa425bee902d0dc5',
    messagingSenderId: '227719515296',
    projectId: 'chatgpt-try-6dc6d',
    authDomain: 'chatgpt-try-6dc6d.firebaseapp.com',
    storageBucket: 'chatgpt-try-6dc6d.firebasestorage.app',
  );
}
